services:
  sandbox:
    build: .
    environment:
      - HOME=/persist
      - PATH=/persist/.local/bin:/root/.local/bin:/usr/local/bin:$PATH
    volumes:
      - ./persist:/persist
    tty: true
    stdin_open: true
